### ISSUE TITLE
Add a logo for the library

### ISSUE THREAD

**Issue by rcardin** [rcardin/sus4s#4]
Add a logo for the library.

**Comment by baldram** [comment]
🤌 We completed the task using a hybrid approach, combining AI and human work. Using GPT-4o/DALL·E and design.com AI for logos, we chose one inspiration from GPT. Though not perfect, it served as a base. After manually refining it in Affinity Designer, we are here.

If you think of a guitar, you're on the right track—the logo references the fact that Sus4 is a guitar chord. The parallel lines in the logo symbolize multitasking and parallel execution.

## Logo and identity specification
### Colors:

| Color       | Hex Code  |
|-------------|-----------|
| Light Blue  | #7EC8E3   |
| Dark Blue   | #0B3D91   |
| White       | #FFFFFF   |
| Black       | #000000   |

## Font:

- Trebuchet MS (free for personal and commercial use)

## Formats:

- Available in SVG and PNG formats

## Usage:

- Two versions of the logo for dark and light mode
- Use specified colors and font consistently in all applications

## Files:

![sus4s-logo-dark-mode](https://github.com/rcardin/sus4s/assets/16861531/68b9fd0e-5483-4129-9b50-fa5907f513f5)

![Sus4s-logo-light-mode](https://github.com/rcardin/sus4s/assets/16861531/332f115d-64cb-419c-bf14-3a33f0d0cf10)

![sus4s-logo-dark-mode](https://github.com/rcardin/sus4s/assets/16861531/ff6ff1fb-fb9f-45fc-a933-59d0036d4a60)

![Sus4s-logo-light-mode](https://github.com/rcardin/sus4s/assets/16861531/be98576b-e5c3-443b-9b67-cf291ecd7b79)
